In [1]:
import pandas as pd 
import numpy as np

In [2]:
date=pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head(6)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3
5  2018-08-23        1811       25       4

In [5]:
time.head(7)

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
5  2016-03-08 22:52:00  пар.32прок.дев.на авто по ночн.городу.Днепр.06...
6  2014-02-18 00:23:00           Семейная пара познакомится для отношений

In [6]:
# when ever we import dataset by dafault it is in form of object or string format  so we santapply  things that we have to do 
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

<h2>WORKING WITH DATES<h2/>

In [9]:
# fisrtly we will focus on date dataset
#converting into date time data type 
date['date']=pd.to_datetime(date['date'])

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

<h3>EXRACT YEAR</h3>

In [14]:
date['date_year']=date['date'].dt.year
date.head(6)

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019
5 2018-08-23        1811       25       4       2018

<h3>EXTRACT MONTH<h3/>

In [15]:
date['date_month'] =date['date'].dt.month 
date.head(6)

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1
5 2018-08-23        1811       25       4       2018           8

In [16]:
date['date_month'] =date['date'].dt.month_name()
date.head(6)

        date  product_id  city_id  orders  date_year date_month
0 2019-12-10        5628       25       3       2019   December
1 2018-08-15        3646       14     157       2018     August
2 2018-10-23        1859       25       1       2018    October
3 2019-08-17        7292       25       1       2019     August
4 2019-01-06        4344       25       3       2019    January
5 2018-08-23        1811       25       4       2018     August

In [22]:
date['date_dayname'] =date['date'].dt.day_name()
date.head(6)

        date  product_id  city_id  orders  date_year date_month date_dayname
0 2019-12-10        5628       25       3       2019    Tuesday      Tuesday
1 2018-08-15        3646       14     157       2018  Wednesday    Wednesday
2 2018-10-23        1859       25       1       2018    Tuesday      Tuesday
3 2019-08-17        7292       25       1       2019   Saturday     Saturday
4 2019-01-06        4344       25       3       2019     Sunday       Sunday
5 2018-08-23        1811       25       4       2018   Thursday     Thursday

In [27]:
date['date_day_week'] =date['date'].dt.dayofweek
date.head(6)

,date,product_id,city_id,orders,date_year,date_month,date_dayname,date_day_week
0,2019-12-10,5628,25,3,2019,Tuesday,Tuesday,1
1,2018-08-15,3646,14,157,2018,Wednesday,Wednesday,2
2,2018-10-23,1859,25,1,2018,Tuesday,Tuesday,1
3,2019-08-17,7292,25,1,2019,Saturday,Saturday,5
4,2019-01-06,4344,25,3,2019,Sunday,Sunday,6
5,2018-08-23,1811,25,4,2018,Thursday,Thursday,3

In [28]:
# is weekend ..?
date['date_is_weakend'] =np.where(date['date_dayname'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head(6)

,date,date_year,date_month,date_dayname,date_day_week,date_is_weakend
0,2019-12-10,2019,Tuesday,Tuesday,1,0
1,2018-08-15,2018,Wednesday,Wednesday,2,0
2,2018-10-23,2018,Tuesday,Tuesday,1,0
3,2019-08-17,2019,Saturday,Saturday,5,1
4,2019-01-06,2019,Sunday,Sunday,6,1
5,2018-08-23,2018,Thursday,Thursday,3,0

<h3>EXTRACT WEAK OF THE YEAR<h3/>

In [30]:
date['date_week']=date['date'].dt.week

AttributeError: 'DatetimeProperties' object has no attribute 'week'

<h3>EXTRACT SEMSTER<h3/>

In [32]:
date['senster']=np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head(6)

KeyError: 'quarter'

<h3>EXTRACT TIME ELAPSED BETWEEN DATES<h3/>

In [38]:
import datetime 
today = datetime.datetime.today
today

In [39]:
today - date['date']

TypeError: unsupported operand type(s) for -: 'DatetimeArray' and 'builtin_function_or_method'

In [41]:
# now we will work on time 
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [42]:
time['date']=pd.to_datetime(time['date'])

In [44]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [48]:
time['hour'] =time['date'].dt.hour
time['minute'] =time['date'].dt.minute
time['second'] =time['date'].dt.second
time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [52]:
time['Time'] =time['date'].dt.time
time.head(6)

,date,msg,hour,minute,second,Time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00
5,2016-03-08 22:52:00,пар.32прок.дев.на авто по ночн.городу.Днепр.06...,22,52,0,22:52:00

In [53]:
# you can many more things those you have to try by yourdelf