In [1]:
import numpy as np

# Create an array (like a list but faster & smarter)
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

# Basic math on whole array at once!
print("Mean (average):", np.mean(arr))
print("Max value:", np.max(arr))
print("Min value:", np.min(arr))
print("Sum:", np.sum(arr))

# 2D Array (like a table)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D Matrix:\n", matrix)
print("Shape (rows, columns):", matrix.shape)

Array: [10 20 30 40 50]
Mean (average): 30.0
Max value: 50
Min value: 10
Sum: 150

2D Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape (rows, columns): (3, 3)

In [2]:
import pandas as pd

# Create your first DataFrame (like an Excel table)
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Zara"],
    "Age": [22, 25, 23, 21],
    "Score": [88, 92, 75, 95],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad"]
}

df = pd.DataFrame(data)
print("Your first DataFrame:")
print(df)

Your first DataFrame:
    Name  Age  Score       City
0    Ali   22     88    Karachi
1   Sara   25     92     Lahore
2  Ahmed   23     75    Karachi
3   Zara   21     95  Islamabad

In [3]:
# See basic info about your data
print("Shape:", df.shape)           # rows, columns
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nBasic stats:\n", df.describe())

Shape: (4, 4)

Column names: ['Name', 'Age', 'Score', 'City']

Data types:
 Name     object
Age       int64
Score     int64
City     object
dtype: object

Basic stats:
              Age      Score
count   4.000000   4.000000
mean   22.750000  87.500000
std     1.707825   8.812869
min    21.000000  75.000000
25%    21.750000  84.750000
50%    22.500000  90.000000
75%    23.500000  92.750000
max    25.000000  95.000000

In [4]:
# Selecting data
print("Just the Name column:")
print(df["Name"])

print("\nJust Age and Score:")
print(df[["Age", "Score"]])

print("\nOnly people from Karachi:")
print(df[df["City"] == "Karachi"])

Just the Name column:
0      Ali
1     Sara
2    Ahmed
3     Zara
Name: Name, dtype: object

Just Age and Score:
   Age  Score
0   22     88
1   25     92
2   23     75
3   21     95

Only people from Karachi:
    Name  Age  Score     City
0    Ali   22     88  Karachi
2  Ahmed   23     75  Karachi

In [5]:
# Useful operations
print("Average score:", df["Score"].mean())
print("Highest score:", df["Score"].max())
print("Who scored highest:", df[df["Score"] == df["Score"].max()]["Name"].values[0])

Average score: 87.5
Highest score: 95
Who scored highest: Zara

In [8]:
df['passed'] =df['Score'].apply(lambda x :'passed' if x >80 else 'fail')

In [9]:
df.head()

    Name  Age  Score       City  passed
0    Ali   22     88    Karachi  passed
1   Sara   25     92     Lahore  passed
2  Ahmed   23     75    Karachi    fail
3   Zara   21     95  Islamabad  passed

In [10]:
df[df['passed']=='passed']

   Name  Age  Score       City  passed
0   Ali   22     88    Karachi  passed
1  Sara   25     92     Lahore  passed
3  Zara   21     95  Islamabad  passed

In [12]:
# Average age of students from Karachi
karachi_students = df[df['City'] == 'Karachi']
print("Average age of Karachi students:", karachi_students['Age'].mean())

Average age of Karachi students: 22.5